### ISSUE TITLE
Support for NextJS?

### ISSUE THREAD

**Issue by timarney** [cds-snc/gcds-components#114]
Does this repo support NextJS?

Tried an integration https://github.com/cds-snc/platform-forms-client/pull/1717 but seeing lots of errors and app fails to load.

**Comment by ethanWallace** [comment]
We did some looking into our web components with NextJS, and depending on the version you have to use an additional plugin with them (https://www.npmjs.com/package/next-transpile-modules).

**Comment by timarney** [comment]
Okay thanks.

Looks like that package is deprecated.

<img width="1235" alt="Screen Shot 2023-03-15 at 8 51 37 AM" src="https://user-images.githubusercontent.com/62242/225314175-e866a308-e213-4be4-bc79-b0a06cdfd185.png">

We're looking to move to Next 13 (https://github.com/cds-snc/platform-forms-client/pull/1563) so I'll close issue and re-visit the integration after we make that move.

**Comment by rgalipeau** [comment]
Just a note that we were able to load the GCDS react components with NextJS 13+
As you mentioned @ethanWallace no longer needs the additional plugin you mentioned, as it newer versions directly supports `transpilePackages`

My config:

**next.config.js**
```
/** @type {import('next').NextConfig} */
const nextConfig = {
  transpilePackages: ["@cdssnc/gcds-components-react"],
  images: {
    domains: [process.env.NEXT_IMAGE_DOMAIN],
  },
}
```

And then from any .tsx when importing, you must specifiy "/dist", or you get misguided errors.
e.g"
`import { GcdsHeader , GcdsTopNav , GcdsNavLink , GcdsNavGroup , GcdsBreadcrumbs , GcdsBreadcrumbsItem} from "@cdssnc/gcds-components-react/dist"
`

**Comment by ethanWallace** [comment]
Thank you @rgalipeau for the additional information.

We hope to release a new `@cdssnc/gcds-components-react-ssr` package soon that will allow our React/web components to take advantage of the server side rendering features in Nextjs because at the current moment the `@cdssnc/gcds-components-react` won't render server side.

As for the having to add `/dist` to your imports, would you be able to submit a GitHub issue about this including the errors you receive if you do not include it? Thank you
